# Generated by Django 5.1.6 on 2025-02-28 09:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_mensajeproyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together={('usuario', 'proyecto')},
        ),
    ]
